# Generated by Django 3.2.8 on 2021-12-02 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_phone', models.CharField(help_text='+255 format', max_length=15)),
                ('mobile_phone', models.CharField(blank=True, help_text='+255 format', max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Freelancer', 'Freelancer')], max_length=50, null=True)),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('Sales Manager', 'Sales Manager'), ('Sales Officer', 'Sales Officer'), ('Secretary', 'Secretary'), ('Marketing Manager', 'Marketing Manager'), ('Marketing Officer', 'Marketing Officer'), ('Accountant', 'Accountant'), ('Financial Manager', 'Financial Manager'), ('Managing Director', 'Managing Director'), ('Director', 'Director'), ('Branch Manager', 'Branch Manager'), ('Operational Manager', 'Operational Manager'), ('Procurement Manager', 'Procurement Manager'), ('Procurement Officer', 'Procurement Officer'), ('Store Officer', 'Store Officer'), ('Assistant Store Officer', 'Assistant Store Officer'), ('Administrative Assistant', 'Administrative Assistant'), ('Operations Manager', 'Operations Manager'), ('Operations Officer', 'Operations Officer'), ('Human Resource Manager', 'Human Resource Manager'), ('Human Resource Officer', 'Human Resource Officer')], max_length=100)),
                ('other_position', models.CharField(blank=True, max_length=100, null=True)),
                ('id_no', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.PositiveIntegerField()),
                ('starting_date', models.DateField()),
                ('contract_period', models.PositiveIntegerField()),
                ('period', models.CharField(blank=True, choices=[('Weeks', 'Weeks'), ('Months', 'Months'), ('Years', 'Years')], max_length=10, null=True)),
                ('nida', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('performance', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_employee', to='administration.business')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='administration.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
